const POSTS_REQUEST_SEND = "POSTS_REQUEST_SEND";
const POSTS_REQUEST_SUCCESS = "POSTS_REQUEST_SUCCESS";
const POSTS_REQUEST_FAILURE = "POSTS_REQUEST_FAILURE";

const COMMENTS_REQUEST_SEND = "COMMENTS_REQUEST_SEND";
const COMMENTS_REQUEST_SUCCESS = "COMMENTS_REQUEST_SUCCESS";
const COMMENTS_REQUEST_FAILURE = "COMMENTS_REQUEST_FAILURE";

const ALBUMS_REQUEST_SEND = "ALBUMS_REQUEST_SEND";
const ALBUMS_REQUEST_SUCCESS = "ALBUMS_REQUEST_SUCCESS";
const ALBUMS_REQUEST_FAILURE = "ALBUMS_REQUEST_FAILURE";

const PHOTOS_REQUEST_SEND = "PHOTOS_REQUEST_SEND";
const PHOTOS_REQUEST_SUCCESS = "PHOTOS_REQUEST_SUCCESS";
const PHOTOS_REQUEST_FAILURE = "PHOTOS_REQUEST_FAILURE";

const SINGLE_POST_REQUEST_SEND = "SINGLE_POST_REQUEST_SEND";
const SINGLE_POST_REQUEST_SUCCESS = "SINGLE_POST_REQUEST_SUCCESS";
const SINGLE_POST_REQUEST_FAILURE = "SINGLE_POST_REQUEST_FAILURE";

export {
    POSTS_REQUEST_SEND,
    POSTS_REQUEST_SUCCESS,
    POSTS_REQUEST_FAILURE,
    COMMENTS_REQUEST_SEND,
    COMMENTS_REQUEST_SUCCESS,
    COMMENTS_REQUEST_FAILURE,
    ALBUMS_REQUEST_SEND,
    ALBUMS_REQUEST_SUCCESS,
    ALBUMS_REQUEST_FAILURE,
    PHOTOS_REQUEST_SEND,
    PHOTOS_REQUEST_SUCCESS,
    PHOTOS_REQUEST_FAILURE,
    SINGLE_POST_REQUEST_SEND,
    SINGLE_POST_REQUEST_SUCCESS,
    SINGLE_POST_REQUEST_FAILURE,
}